app = "auth-service-academy"
primary_region = "gru"

[build]

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

[[http_service.checks]]
  grace_period = "30s"
  interval = "15s"
  method = "GET"
  path = "/auth/health"
  timeout = "10s"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
