app = "auth-service-academy"
primary_region = "gru"

[build]

[env]
  CORS_ALLOWED_ORIGINS = "https://learnsoft.uy,https://www.learnsoft.uy"
  ANALYTICS_REQUEST_TRACKING_ENABLED = "false"
  ANALYTICS_RETENTION_DAYS = "30"

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1

[[http_service.checks]]
  grace_period = "30s"
  interval = "15s"
  method = "GET"
  path = "/auth/health"
  timeout = "10s"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
